//Inicializamos la variable costantes la cual
//es utilizada por los actions y reducers
const constantes = {
  CAMBIAR_CANTIDAD_ORIGENES: "CAMBIAR_CANTIDAD_ORIGENES", //CHANGE_ROWS_COUNT
  CAMBIAR_CANTIDAD_DESTINOS: "CAMBIAR_CANTIDAD_DESTINOS", //CHANGE_COLUMNS_COUNT
  ACTUALIZAR_MATRIZ: "ACTUALIZAR_MATRIZ", //UPDATE_MATRIX
  CAMBIAR_DEMANDAS: "CAMBIAR_DEMANDAS", //CHANGE_NEEDS
  CAMBIAR_OFERTAS: "CAMBIAR_OFERTAS", //CHANGE_STORAGE

  OBTENER_OFERTA_VOLUME: "OBTENER_OFERTA_VOLUME", //GET_STORAGE_VOLUME
  OBTENER_DEMANDA_VOLUME: "OBTENER_DEMANDA_VOLUME", //GET_NEEDS_VOLUME
  UPDATE_STATE: "UPDATE_STATE"
};

export default constantes;
